### ISSUE TITLE
Go through all current page text & finalize

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#213]
^..^      /
/_/\_____/
   /\   /\
  /  \ /  \ (_squished ASCII dig does not look like dog_)

- [x] About
- [x] Accessibility: not done, but #9 assigns this to Amanda for after accessibility testing/final-ish design decisions made
- [x] Blog
- [x] Charter
- [x] Cultural Heritage Informatics Internship
- [x] Colophon: not done, but issue #16 assigns this to Jeremy
- [x] Digital Humanities Fellows Program
- [x] Events
- [x] FAQ
- [x] Scholars' Lab GIS Technician
- [x] Hours and Spaces
- [x] Home: not done, but issues #232 #230 #228 #96 cover the needed work
- [x] Library
- [x] Makerspace Technologists
- [x] Makerspace
- [x] People
- [x] Posts by Tag
- [x] Praxis Program Fellowships
- [x] Professional Development
- [x] Progress Tracker: removed page
- [x] Digital Humanities Prototyping Fellowships
- [x] Scholarship; not done, but #263 covers the needed work
- [x] Search
- [x] Site Map
- [x] Spatial Tech: not done, but @lam2c is doing this in issue #96 
- [x] Pedagogy
- [x] Guest DH Workshop Teaching at W&L

**Comment by amandavisconti** [comment]
just need to push local after #263 to complete this, alert team pages ready for proofing
